
      run: |
        dotnet test --verbosity normal --configuration=MacRelease

    - name: Prepare artifacts
      run: |
        mkdir -p artifacts/bin
        mv out/osx/Installer.Mac/pkg/Release/payload "artifacts/bin/${{ matrix.runtime }}"
        cp out/osx/Installer.Mac/pkg/Release/payload.sym/* "artifacts/bin/${{ matrix.runtime }}/"
        mv out/osx/Installer.Mac/pkg/Release/gcm*.pkg artifacts/

    - 

